/*                        Step 3: Load Phonemes                        */

/* Fill In Phoneme Table */
INSERT ALL
    --Labial Consonants
    INTO Phonemes VALUES ('p', 1)
    INTO Phonemes VALUES ('P', 1)
    INTO Phonemes VALUES ('b', 1)
    INTO Phonemes VALUES ('m', 1)
    INTO Phonemes VALUES ('w', 1)
    --Coronal Consonants
    INTO Phonemes VALUES ('θ', 1)
    INTO Phonemes VALUES ('t', 1)
    INTO Phonemes VALUES ('T', 1)
    INTO Phonemes VALUES ('d', 1)
    INTO Phonemes VALUES ('D', 1)
    INTO Phonemes VALUES ('s', 1)
    INTO Phonemes VALUES ('S', 1)
    INTO Phonemes VALUES ('ʃ', 1)
    INTO Phonemes VALUES ('n', 1)
    INTO Phonemes VALUES ('l', 1)
    INTO Phonemes VALUES ('r', 1)
    INTO Phonemes VALUES ('ɲ', 1)
    INTO Phonemes VALUES ('j', 1)
    --Velar Consonants
    INTO Phonemes VALUES ('k', 1)
    INTO Phonemes VALUES ('K', 1)
    INTO Phonemes VALUES ('g', 1)
    INTO Phonemes VALUES ('x', 1)
    INTO Phonemes VALUES ('ŋ', 1)
    INTO Phonemes VALUES ('X', 1)
    INTO Phonemes VALUES ('ʔ', 1)
    INTO Phonemes VALUES ('h', 1)
    --Vowels
    INTO Phonemes VALUES ('i', 0)
    INTO Phonemes VALUES ('ɪ', 0)
    INTO Phonemes VALUES ('u', 0)
    INTO Phonemes VALUES ('e', 0)
    INTO Phonemes VALUES ('ɛ', 0)
    INTO Phonemes VALUES ('ə', 0)
    INTO Phonemes VALUES ('o', 0)
    INTO Phonemes VALUES ('ɔ', 0)
    INTO Phonemes VALUES ('a', 0)
SELECT 1 FROM dual;

/* Fill in Consonants Table */
INSERT ALL
  --Unaspirated, Non-Nasal, Non-lateral
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('p', 'stop', 'labial', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('b', 'stop', 'labial', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('w', 'approximant', 'labio-velar', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('θ', 'fricative', 'dental', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('t', 'stop', 'alveolar', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('d', 'stop', 'alveolar', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('s', 'fricative', 'alveolar', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('ʃ', 'fricative', 'post-alveolar', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('r', 'trill', 'alveolar', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('j', 'approximant', 'palatal', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('k', 'stop', 'velar', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('g', 'stop', 'velar', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('x', 'fricative', 'velar', 0)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('X', 'approximant', 'velar', 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced)
        VALUES ('ʔ', 'stop', 'glottal', 0)
  --Aspirated
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsAspirated)
        VALUES ('P', 'stop', 'labial', 0, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsAspirated)
        VALUES ('T', 'stop', 'alveolar', 0, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsAspirated)
        VALUES ('D', 'stop', 'alveolar', 1, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsAspirated)
        VALUES ('S', 'fricative', 'alveolar', 0, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsAspirated)
        VALUES ('K', 'stop', 'velar', 0, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsAspirated)
        VALUES ('h', 'fricative', 'glottal', 0, 1)
  --Nasal
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsNasal)
        VALUES ('m', 'stop', 'labial', 1, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsNasal)
        VALUES ('n', 'stop', 'alveolar', 1, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsNasal)
        VALUES ('ɲ', 'stop', 'palatal', 1, 1)
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsNasal)
        VALUES ('ŋ', 'stop', 'velar', 1, 1)
  --Lateral
    INTO Consonants (IPA, Manner, Place, IsVoiced, IsLateral)
        VALUES ('l', 'approximant', 'alveolar', 1, 1)
SELECT 1 FROM dual;
        
/* Fill in Vowels Table */
INSERT ALL
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('i', 'high', 'front', 1)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('ɪ', 'high', 'central', 1)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('u', 'high', 'back', 1)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('e', 'mid', 'front', 1)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('ɛ', 'mid', 'front', 0)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('ə', 'mid', 'central', 0)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('o', 'mid', 'back', 1)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('ɔ', 'mid', 'back', 0)
    INTO Vowels (IPA, Height, Backness, IsTense)
        VALUES ('a', 'low', 'central', 1)
SELECT 1 FROM dual;
