UPDATE Karen_Words SET Pron = 'po mu' WHERE Word_ID = 56;
UPDATE Karen_Words SET Pron = 'pwa kə ɲo' WHERE Word_ID = 58;
UPDATE Karen_Words SET Pron = 'də ku θə ru: ku' WHERE Word_ID = 60;
UPDATE Karen_Words SET Pron = 'klo te', Tone = '55 214' WHERE Word_ID = 65;
UPDATE Karen_Words SET Pron = 'ko ko', Tone = '51 51' WHERE Word_ID = 66;
UPDATE Karen_Words SET Pron = 'ko ke re ke' WHERE Word_ID = 67;
UPDATE Karen_Words SET Pron = 'ku te', Tone = '55 214' WHERE Word_ID = 68;
UPDATE Karen_Words SET Pron = 'li po ʔɑ', Tone = '51 ??' WHERE Word_ID = 69;
UPDATE Karen_Words SET Pron = 'lo te', Tone = '51 214' WHERE Word_ID = 71;
UPDATE Karen_Words SET Pron = 'me o' WHERE Word_ID = 72;
UPDATE Karen_Words SET Pron = 'bo ɹu Pe', Tone = '11 11 55' WHERE Word_ID = 77;
UPDATE Karen_Words SET Pron = 'hɑ To li' WHERE Word_ID = 78;
UPDATE Karen_Words SET Pron = 'hi ni mo tɑ' WHERE Word_ID = 80;
UPDATE Karen_Words SET Pron = 'ke li' WHERE Word_ID = 83;
UPDATE Karen_Words SET Pron = 'kə mɑ Po' WHERE Word_ID = 84;
UPDATE Karen_Words SET Pron = 'kə sə', Tone = '51 ??' WHERE Word_ID = 85;
UPDATE Karen_Words SET Pron = 'kə ti tə pwe' WHERE Word_ID = 86;
UPDATE Karen_Words SET Pron = 'Kɔ kə me', Tone = '51 ?? ??' WHERE Word_ID = 92;
UPDATE Karen_Words SET Pron = 'Kɔ le Kɔ', Tone = '51 ?? 51' WHERE Word_ID = 93;
UPDATE Karen_Words SET Pron = 'Kɔ ɲɑ Ko', Tone = '51 ?? 51' WHERE Word_ID = 94;
UPDATE Karen_Words SET Pron = 'Kɔ nə Ki', Tone = '51 51 ??' WHERE Word_ID = 95;
UPDATE Karen_Words SET Pron = 'Kɔ Pi', Tone = '51 ??' WHERE Word_ID = 96;
UPDATE Karen_Words SET Pron = 'Kɔ tɔ tə kɔ', Tone = '51 55 11 55' WHERE Word_ID = 97;
UPDATE Karen_Words SET Pron = 'Kɔ tɔ tə kə bɑ', Tone = '51 55 11 11 55' WHERE Word_ID = 98;
UPDATE Karen_Words SET Pron = 'Kɔ Pju Təɹ' WHERE Word_ID = 99;
UPDATE Karen_Words SET Pron = 'Kɔ ʧu' WHERE Word_ID = 100;
UPDATE Karen_Words SET Pron = 'Kɔ θu' WHERE Word_ID = 101;
UPDATE Karen_Words SET Pron = 'Ko kə me' WHERE Word_ID = 107;
UPDATE Karen_Words SET Pron = 'Ko Ki tu' WHERE Word_ID = 108;
UPDATE Karen_Words SET Pron = 'Ko nə Ki' WHERE Word_ID = 111;
UPDATE Karen_Words SET Pron = 'Ko Pi' WHERE Word_ID = 113;
UPDATE Karen_Words SET Pron = 'Ko θu' WHERE Word_ID = 114;
UPDATE Karen_Words SET Pron = 'Ku lu to' WHERE Word_ID = 115;
UPDATE Karen_Words SET Pron = 'ko po' WHERE Word_ID = 125;
UPDATE Karen_Words SET Pron = 'lɔ Kɔ' WHERE Word_ID = 128;
UPDATE Karen_Words SET Pron = 'lɔ ʧe nɔ' WHERE Word_ID = 129;
UPDATE Karen_Words SET Pron = 'lə θe pɑ' WHERE Word_ID = 132;
UPDATE Karen_Words SET Pron = 'lo mi to pu' WHERE Word_ID = 133;
UPDATE Karen_Words SET Pron = 'lo mi Ko' WHERE Word_ID = 134;
UPDATE Karen_Words SET Pron = 'lo ti tə kɑ' WHERE Word_ID = 135;
UPDATE Karen_Words SET Pron = 'lo ti to lo' WHERE Word_ID = 136;
UPDATE Karen_Words SET Pron = 'mɑ tɑ lə ki lə pɑ' WHERE Word_ID = 139;
UPDATE Karen_Words SET Pron = 'me ʔu tə', Tone = '51 51 ??' WHERE Word_ID = 143;
UPDATE Karen_Words SET Pron = 'me ʔu tə' WHERE Word_ID = 144;
UPDATE Karen_Words SET Pron = 'mi Ke' WHERE Word_ID = 147;
UPDATE Karen_Words SET Pron = 'mi ki' WHERE Word_ID = 148;
UPDATE Karen_Words SET Pron = 'mo mi θɑ' WHERE Word_ID = 149;
UPDATE Karen_Words SET Pron = 'mo ʔu tə' WHERE Word_ID = 150;
UPDATE Karen_Words SET Pron = 'ne ʔa ɰi su no' WHERE Word_ID = 153;
UPDATE Karen_Words SET Pron = 'no ke', Tone = '51 55' WHERE Word_ID = 155;
UPDATE Karen_Words SET Pron = 'pɑ ɹə Pe' WHERE Word_ID = 156;
UPDATE Karen_Words SET Pron = 'pe ðro', Tone = '55 51' WHERE Word_ID = 158;
UPDATE Karen_Words SET Pron = 'Pɑ kə pu' WHERE Word_ID = 162;
UPDATE Karen_Words SET Pron = 'Plə Tu', Tone = '51 ??' WHERE Word_ID = 165;
UPDATE Karen_Words SET Pron = 'Plo Ki', Tone = '51 ??' WHERE Word_ID = 167;
UPDATE Karen_Words SET Pron = 'sɔ nɔ Kɔ' WHERE Word_ID = 180;
UPDATE Karen_Words SET Pron = 'sə po', Tone = '51 55' WHERE Word_ID = 181;
UPDATE Karen_Words SET Pron = 'sə po' WHERE Word_ID = 182;
UPDATE Karen_Words SET Pron = 'so no ko' WHERE Word_ID = 185;
UPDATE Karen_Words SET Pron = 'tɑ lɑ Ti lə' WHERE Word_ID = 193;
UPDATE Karen_Words SET Pron = 'tɑ nɑ ne ʔɑ tə θi' WHERE Word_ID = 196;
UPDATE Karen_Words SET Pron = 'tɑ nɑ ni ʔɑ θi' WHERE Word_ID = 197;
UPDATE Karen_Words SET Pron = 'tə Po Ko' WHERE Word_ID = 210;
UPDATE Karen_Words SET Pron = 'tə ti tə' WHERE Word_ID = 211;
UPDATE Karen_Words SET Pron = 'tə θu' WHERE Word_ID = 212;
UPDATE Karen_Words SET Pron = 'Ti se' WHERE Word_ID = 219;
UPDATE Karen_Words SET Pron = 'Tu to' WHERE Word_ID = 221;
UPDATE Karen_Words SET Pron = 'θɑ mi ɲo' WHERE Word_ID = 234;
UPDATE Karen_Words SET Pron = 'θe ɲɑ Po tɑ' WHERE Word_ID = 244;
UPDATE Karen_Words SET Pron = 'θə pe hɑ lɑ' WHERE Word_ID = 245;
UPDATE Karen_Words SET Pron = 'θə ta lə' WHERE Word_ID = 246;
UPDATE Karen_Words SET Pron = 'θe Tu' WHERE Word_ID = 247;
UPDATE Karen_Words SET Pron = 'θu to θɑ to' WHERE Word_ID = 249;
UPDATE Karen_Words SET Pron = 'θu wo θɑ ko' WHERE Word_ID = 250;
UPDATE Karen_Words SET Pron = 'a wɛ θe ha lə mə ha' WHERE Word_ID = 253;
UPDATE Karen_Words SET Pron = 'ɑ wɛ θeʔ kə lə na' WHERE Word_ID = 254;
UPDATE Karen_Words SET Pron = 'a θi θo' WHERE Word_ID = 255;
UPDATE Karen_Words SET Pron = 'bu mu ʝo' WHERE Word_ID = 258;
UPDATE Karen_Words SET Pron = 'ə ʁo' WHERE Word_ID = 263;
UPDATE Karen_Words SET Pron = 'i θa' WHERE Word_ID = 264;
UPDATE Karen_Words SET Pron = 'i θa Sɤ' WHERE Word_ID = 265;
UPDATE Karen_Words SET Pron = 'ka nu Ti' WHERE Word_ID = 266;
UPDATE Karen_Words SET Pron = 'kɔ ʔɔʔ' WHERE Word_ID = 267;
UPDATE Karen_Words SET Pron = 'Ka lə kə hɛʔ' WHERE Word_ID = 268;
UPDATE Karen_Words SET Pron = 'Kɛ mu seʔ' WHERE Word_ID = 269;
UPDATE Karen_Words SET Pron = 'ko pɔ mo' WHERE Word_ID = 273;
UPDATE Karen_Words SET Pron = 'ku θaʔ' WHERE Word_ID = 274;
UPDATE Karen_Words SET Pron = 'la paʔ' WHERE Word_ID = 276;
UPDATE Karen_Words SET Pron = 'lɔ θa ka' WHERE Word_ID = 277;
UPDATE Karen_Words SET Pron = 'mu hɛ θa' WHERE Word_ID = 281;
UPDATE Karen_Words SET Pron = 'mu hɛ θa' WHERE Word_ID = 281;
UPDATE Karen_Words SET Pron = 'na pɔ mi Pɔ' WHERE Word_ID = 283;
UPDATE Karen_Words SET Pron = 'nə kə lə ha lə mə haʔ' WHERE Word_ID = 285;
UPDATE Karen_Words SET Pron = 'nə Pɔ' WHERE Word_ID = 286;
UPDATE Karen_Words SET Pron = 'nə θu kə lə na' WHERE Word_ID = 287;
UPDATE Karen_Words SET Pron = 'pə nəʔ' WHERE Word_ID = 289;
UPDATE Karen_Words SET Pron = 'pə θə ʁo' WHERE Word_ID = 291;
UPDATE Karen_Words SET Pron = 'pə θə wa' WHERE Word_ID = 292;
UPDATE Karen_Words SET Pron = 'ta dɔ ta la' WHERE Word_ID = 296;
UPDATE Karen_Words SET Pron = 'ta di' WHERE Word_ID = 297;
UPDATE Karen_Words SET Pron = 'ta ha ɲa ʔe' WHERE Word_ID = 298;
UPDATE Karen_Words SET Pron = 'ta ha ɲa ʔe' WHERE Word_ID = 299;
UPDATE Karen_Words SET Pron = 'ta jo Ka lɔ' WHERE Word_ID = 300;
UPDATE Karen_Words SET Pron = '̪̪ta nu Ti' WHERE Word_ID = 302;
UPDATE Karen_Words SET Pron = 'ta su Ka dɔ' WHERE Word_ID = 303;
UPDATE Karen_Words SET Pron = 'ta ʔɔ' WHERE Word_ID = 304;
UPDATE Karen_Words SET Pron = '̪tə kɔʔ θaʔ' WHERE Word_ID = 305;
UPDATE Karen_Words SET Pron = 'tə na ɲa ʔe Ta Tɔ muʔ' WHERE Word_ID = 306;
UPDATE Karen_Words SET Pron = 'tə ʁo ɲa ʔe' WHERE Word_ID = 307;
UPDATE Karen_Words SET Pron = 'tə θu Tiʔ' WHERE Word_ID = 308;
UPDATE Karen_Words SET Pron = 'Tɔ ba' WHERE Word_ID = 309;
UPDATE Karen_Words SET Pron = 'ʔʌ wɛ θe' WHERE Word_ID = 315;
UPDATE Karen_Words SET Pron = 'θo leʔ' WHERE Word_ID = 317;
UPDATE Karen_Words SET Pron = 'θo lə ʔə ʔə nu θo leʔ' WHERE Word_ID = 318;
UPDATE Karen_Words SET Pron = 'θo ʔɔʔ' WHERE Word_ID = 319;
UPDATE Karen_Words SET Pron = 'θo ʔɔʔ' WHERE Word_ID = 319;
UPDATE Karen_Words SET Pron = 'θu lɔ' WHERE Word_ID = 321;
UPDATE Karen_Words SET Pron = 'kə mu se' WHERE Word_ID = 379;
INSERT INTO Variants (Word_ID, VarPron) VALUES (379, 'mu se');
UPDATE Karen_Words SET Pron = 'ta shə kə tɒ' WHERE Word_ID = 380;
INSERT INTO Variants (Word_ID, VarPron) VALUES (380, 'shə kə tɒ');
UPDATE Karen_Words SET Pron = 'a ɣe' WHERE Word_ID = 382;
UPDATE Karen_Words SET Pron = 'ba ɣi ma' WHERE Word_ID = 387;
INSERT INTO Variants (Word_ID, VarPron) VALUES (387, 'ba ɣi');
UPDATE Karen_Words SET Pron = 'ə ko' WHERE Word_ID = 393;
UPDATE Karen_Words SET Pron = 'kə kɛ thɒ' WHERE Word_ID = 409;
UPDATE Karen_Words SET Pron = 'kə lu' WHERE Word_ID = 410;
UPDATE Karen_Words SET Pron = 'kwa ja' WHERE Word_ID = 413;
UPDATE Karen_Words SET Pron = 'mi no' WHERE Word_ID = 433;
UPDATE Karen_Words SET Pron = 'mu kə nɒ pwa' WHERE Word_ID = 437;
UPDATE Karen_Words SET Pron = 'ɲa bu te' WHERE Word_ID = 440;
UPDATE Karen_Words SET Pron = 'ɲa go me' WHERE Word_ID = 441;
UPDATE Karen_Words SET Pron = 'ɲa po lo' WHERE Word_ID = 442;
UPDATE Karen_Words SET Pron = 'pə lu wi' WHERE Word_ID = 453;
UPDATE Karen_Words SET Pron = 'po we' WHERE Word_ID = 460;
UPDATE Karen_Words SET Pron = 'pwa te ta ʔu ta po' WHERE Word_ID = 463;
UPDATE Karen_Words SET Pron = 'pwa θa wi ta po' WHERE Word_ID = 464;
UPDATE Karen_Words SET Pron = 'ta ma' WHERE Word_ID = 475;
UPDATE Karen_Words SET Pron = 'ta tə mi mi' WHERE Word_ID = 477;
UPDATE Karen_Words SET Pron = 'ta ti ta ʔu' WHERE Word_ID = 478;
UPDATE Karen_Words SET Pron = 'ta θa wi' WHERE Word_ID = 479;
UPDATE Karen_Words SET Pron = 'ta θu wi θa sa' WHERE Word_ID = 480;
UPDATE Karen_Words SET Pron = 'tə pu' WHERE Word_ID = 484;
UPDATE Karen_Words SET Pron = 'ʔa ɣo' WHERE Word_ID = 496;
UPDATE Karen_Words SET Pron = 'ʔi li' WHERE Word_ID = 503;
UPDATE Karen_Words SET Pron = 'θa wi ta' WHERE Word_ID = 508;
UPDATE Karen_Words SET Pron = 'θa wi ta' WHERE Word_ID = 508;
UPDATE Karen_Words SET Pron = 'θe ɲa' WHERE Word_ID = 512;
UPDATE Karen_Words SET Pron = 'ɓɑ ɣe ɣě' WHERE Word_ID = 514;
UPDATE Karen_Words SET Pron = 'də mi mi' WHERE Word_ID = 525;
UPDATE Karen_Words SET Pron = 'ke ju' WHERE Word_ID = 542;
UPDATE Karen_Words SET Pron = 'sə mu la' WHERE Word_ID = 604;
UPDATE Karen_Words SET Pron = 'se və tɔ pε lε' WHERE Word_ID = 605;
UPDATE Karen_Words SET Pron = 'So kə mɔ' WHERE Word_ID = 607;
UPDATE Karen_Words SET Pron = 'ta ʔə' WHERE Word_ID = 620;
UPDATE Karen_Words SET Pron = 'ta θa wiʔ' WHERE Word_ID = 621;
UPDATE Karen_Words SET Pron = 'θa ku' WHERE Word_ID = 654;
UPDATE Karen_Words SET Pron = 'θa wi' WHERE Word_ID = 655;
UPDATE Karen_Words SET Pron = 'θu ku θa ɣɔ' WHERE Word_ID = 659;
UPDATE Karen_Words SET Pron = 'a lu a pu' WHERE Word_ID = 663;
UPDATE Karen_Words SET Pron = 'a lʌ se nɔ' WHERE Word_ID = 664;
UPDATE Karen_Words SET Pron = 'a ɲa' WHERE Word_ID = 665;
UPDATE Karen_Words SET Pron = 'a ni de' WHERE Word_ID = 666;
UPDATE Karen_Words SET Pron = 'a pu' WHERE Word_ID = 667;
UPDATE Karen_Words SET Pron = 'a ta' WHERE Word_ID = 668;
UPDATE Karen_Words SET Pron = 'a tɔ' WHERE Word_ID = 669;
UPDATE Karen_Words SET Pron = 'a we po kwa' WHERE Word_ID = 670;
UPDATE Karen_Words SET Pron = 'a we po mu' WHERE Word_ID = 671;
UPDATE Karen_Words SET Pron = 'a θa bo a' WHERE Word_ID = 672;
UPDATE Karen_Words SET Pron = 'da ne' WHERE Word_ID = 674;
UPDATE Karen_Words SET Pron = 'de mu' WHERE Word_ID = 676;
UPDATE Karen_Words SET Pron = 'de po' WHERE Word_ID = 677;
UPDATE Karen_Words SET Pron = 'di se' WHERE Word_ID = 678;
UPDATE Karen_Words SET Pron = 'do da re' WHERE Word_ID = 679;
UPDATE Karen_Words SET Pron = 'do ma' WHERE Word_ID = 680;
UPDATE Karen_Words SET Pron = 'do ne' WHERE Word_ID = 681;
UPDATE Karen_Words SET Pron = 'du me' WHERE Word_ID = 682;
UPDATE Karen_Words SET Pron = 'dʌ pa pa' WHERE Word_ID = 683;
UPDATE Karen_Words SET Pron = 'ə pu' WHERE Word_ID = 685;
UPDATE Karen_Words SET Pron = 'ha go' WHERE Word_ID = 687;
UPDATE Karen_Words SET Pron = 'i mi ti' WHERE Word_ID = 690;
UPDATE Karen_Words SET Pron = 'jə ri to' WHERE Word_ID = 691;
UPDATE Karen_Words SET Pron = 'ka bɔ' WHERE Word_ID = 694;
UPDATE Karen_Words SET Pron = 'kɔ ʧe' WHERE Word_ID = 695;
UPDATE Karen_Words SET Pron = 'kə mu kə ma' WHERE Word_ID = 696;
UPDATE Karen_Words SET Pron = 'kə pu θu su' WHERE Word_ID = 697;
UPDATE Karen_Words SET Pron = 'kə ti lu θa' WHERE Word_ID = 698;
UPDATE Karen_Words SET Pron = 'Ka Pa' WHERE Word_ID = 699;
UPDATE Karen_Words SET Pron = 'ki ka lʌ' WHERE Word_ID = 700;
UPDATE Karen_Words SET Pron = 'kle ne bɔ' WHERE Word_ID = 701;
UPDATE Karen_Words SET Pron = 'kli se' WHERE Word_ID = 703;
UPDATE Karen_Words SET Pron = 'ko ʌ he da' WHERE Word_ID = 704;
UPDATE Karen_Words SET Pron = 'ko pɔ θa' WHERE Word_ID = 705;
UPDATE Karen_Words SET Pron = 'ko pu' WHERE Word_ID = 706;
UPDATE Karen_Words SET Pron = 'ko tu tu' WHERE Word_ID = 707;
UPDATE Karen_Words SET Pron = 'ko θa' WHERE Word_ID = 708;
UPDATE Karen_Words SET Pron = 'ko θa' WHERE Word_ID = 708;
UPDATE Karen_Words SET Pron = 'ko θa ri' WHERE Word_ID = 709;
UPDATE Karen_Words SET Pron = 'ko θa ri' WHERE Word_ID = 709;
UPDATE Karen_Words SET Pron = 'ku ki' WHERE Word_ID = 710;
UPDATE Karen_Words SET Pron = 'kʌ pu jet' WHERE Word_ID = 711;
UPDATE Karen_Words SET Pron = 'lɔ ni' WHERE Word_ID = 713;
UPDATE Karen_Words SET Pron = 'le li o' WHERE Word_ID = 716;
UPDATE Karen_Words SET Pron = 'li lɔ pli' WHERE Word_ID = 717;
UPDATE Karen_Words SET Pron = 'lu tu klu' WHERE Word_ID = 718;
UPDATE Karen_Words SET Pron = 'lʌ ʧi na' WHERE Word_ID = 719;
UPDATE Karen_Words SET Pron = 'ma do' WHERE Word_ID = 720;
UPDATE Karen_Words SET Pron = 'ma re' WHERE Word_ID = 721;
UPDATE Karen_Words SET Pron = 'me a ni' WHERE Word_ID = 723;
UPDATE Karen_Words SET Pron = 'me lɔ Ta Por' WHERE Word_ID = 724;
UPDATE Karen_Words SET Pron = 'me ti' WHERE Word_ID = 725;
UPDATE Karen_Words SET Pron = 'mu sə' WHERE Word_ID = 726;
UPDATE Karen_Words SET Pron = 'mu ʧa' WHERE Word_ID = 727;
UPDATE Karen_Words SET Pron = 'na de' WHERE Word_ID = 729;
UPDATE Karen_Words SET Pron = 'na hi' WHERE Word_ID = 730;
UPDATE Karen_Words SET Pron = 'ne de' WHERE Word_ID = 731;
UPDATE Karen_Words SET Pron = 'ni kɔ mu i' WHERE Word_ID = 733;
UPDATE Karen_Words SET Pron = 'pa a so pa' WHERE Word_ID = 736;
UPDATE Karen_Words SET Pron = 'pa do' WHERE Word_ID = 737;
UPDATE Karen_Words SET Pron = 'pa ja' WHERE Word_ID = 738;
UPDATE Karen_Words SET Pron = 'Pa du' WHERE Word_ID = 741;
UPDATE Karen_Words SET Pron = 'plɔ ʧi me' WHERE Word_ID = 743;
UPDATE Karen_Words SET Pron = 'ple li' WHERE Word_ID = 744;
UPDATE Karen_Words SET Pron = 'pli ta' WHERE Word_ID = 745;
UPDATE Karen_Words SET Pron = 'po ma' WHERE Word_ID = 746;
UPDATE Karen_Words SET Pron = 'ri su pa sa' WHERE Word_ID = 748;
UPDATE Karen_Words SET Pron = 'ʁo ʁa' WHERE Word_ID = 749;
UPDATE Karen_Words SET Pron = 'ta ko ti lə' WHERE Word_ID = 750;
UPDATE Karen_Words SET Pron = 'ta pa li o lʌ' WHERE Word_ID = 751;
UPDATE Karen_Words SET Pron = 'ta sa ta ti la' WHERE Word_ID = 752;
UPDATE Karen_Words SET Pron = 'Ta yu mu' WHERE Word_ID = 753;
UPDATE Karen_Words SET Pron = 'to ma' WHERE Word_ID = 757;
UPDATE Karen_Words SET Pron = 'to pa' WHERE Word_ID = 758;
UPDATE Karen_Words SET Pron = 'ʧi no mu' WHERE Word_ID = 759;
UPDATE Karen_Words SET Pron = 'ʧi ʧi po' WHERE Word_ID = 760;
UPDATE Karen_Words SET Pron = 'ʌ Ko Pa' WHERE Word_ID = 767;
UPDATE Karen_Words SET Pron = 'ʌ li lo' WHERE Word_ID = 770;
UPDATE Karen_Words SET Pron = 'ʌ pɔ la' WHERE Word_ID = 772;
UPDATE Karen_Words SET Pron = 'ʌ ʁi pa' WHERE Word_ID = 776;
UPDATE Karen_Words SET Pron = 'ʌ ʁi su' WHERE Word_ID = 777;
UPDATE Karen_Words SET Pron = 'ʌ se hi' WHERE Word_ID = 778;
UPDATE Karen_Words SET Pron = 'wi θa su' WHERE Word_ID = 783;
UPDATE Karen_Words SET Pron = 'θa o' WHERE Word_ID = 784;
UPDATE Karen_Words SET Pron = 'θa da Ta' WHERE Word_ID = 786;
UPDATE Karen_Words SET Pron = 'θa hɔ' WHERE Word_ID = 787;
UPDATE Karen_Words SET Pron = 'θa kɔ' WHERE Word_ID = 788;
UPDATE Karen_Words SET Pron = 'θa su ɲo' WHERE Word_ID = 789;
UPDATE Karen_Words SET Pron = 'θa ʔu' WHERE Word_ID = 790;
UPDATE Karen_Words SET Pron = 'θe la lo' WHERE Word_ID = 791;
UPDATE Karen_Words SET Pron = 'θe ni ta' WHERE Word_ID = 792;
UPDATE Karen_Words SET Pron = 'θe tu' WHERE Word_ID = 794;
UPDATE Karen_Words SET Pron = 'o mu' WHERE Word_ID = 851;
UPDATE Karen_Words SET Pron = 'o mu ti' WHERE Word_ID = 852;
UPDATE Karen_Words SET Pron = 'pa sa' WHERE Word_ID = 853;
UPDATE Karen_Words SET Pron = 'pwa ki ŋo ʔæ so' WHERE Word_ID = 880;
UPDATE Karen_Words SET Pron = 'θu ʔu θa ʔu' WHERE Word_ID = 940;
UPDATE Karen_Words SET Pron = 'θu ʔu θa ʔu' WHERE Word_ID = 941;
UPDATE Karen_Words SET Pron = 'ɣɔ Kɔ' WHERE Word_ID = 946;
UPDATE Karen_Words SET Pron = 'ɣɔ ta ʔɔ' WHERE Word_ID = 947;
UPDATE Karen_Words SET Pron = 'ha ha' WHERE Word_ID = 949;
UPDATE Karen_Words SET Pron = 'ha tɔ' WHERE Word_ID = 951;
UPDATE Karen_Words SET Pron = 'hɛ tu' WHERE Word_ID = 953;
UPDATE Karen_Words SET Pron = 'Ke ju' WHERE Word_ID = 960;
UPDATE Karen_Words SET Pron = 'Kɛ mu Se' WHERE Word_ID = 961;
UPDATE Karen_Words SET Pron = 'klə ma' WHERE Word_ID = 965;
UPDATE Karen_Words SET Pron = 'kle mu' WHERE Word_ID = 966;
UPDATE Karen_Words SET Pron = 'ko Sə kə tɔ te' WHERE Word_ID = 971;
UPDATE Karen_Words SET Pron = 'ko mi' WHERE Word_ID = 972;
UPDATE Karen_Words SET Pron = 'ko mi te' WHERE Word_ID = 973;
UPDATE Karen_Words SET Pron = 'ko mi te' WHERE Word_ID = 973;
UPDATE Karen_Words SET Pron = 'la ho' WHERE Word_ID = 980;
UPDATE Karen_Words SET Pron = 'la Ku' WHERE Word_ID = 982;
UPDATE Karen_Words SET Pron = 'la nɔ' WHERE Word_ID = 983;
UPDATE Karen_Words SET Pron = 'la ʔə' WHERE Word_ID = 986;
UPDATE Karen_Words SET Pron = 'le Ko' WHERE Word_ID = 989;
UPDATE Karen_Words SET Pron = 'lə ne ja' WHERE Word_ID = 990;
UPDATE Karen_Words SET Pron = 'li me ʔu' WHERE Word_ID = 992;
UPDATE Karen_Words SET Pron = 'li me ʔu θə ne' WHERE Word_ID = 994;
UPDATE Karen_Words SET Pron = 'lu ti' WHERE Word_ID = 996;
UPDATE Karen_Words SET Pron = 'ma kə ʃa' WHERE Word_ID = 997;
UPDATE Karen_Words SET Pron = 'ma wi' WHERE Word_ID = 999;
UPDATE Karen_Words SET Pron = 'mə ha kə' WHERE Word_ID = 1000;
UPDATE Karen_Words SET Pron = 'mɛ θa' WHERE Word_ID = 1001;
UPDATE Karen_Words SET Pron = 'mi ni tə Si' WHERE Word_ID = 1002;
UPDATE Karen_Words SET Pron = 'mu bu' WHERE Word_ID = 1003;
UPDATE Karen_Words SET Pron = 'mu də' WHERE Word_ID = 1004;
UPDATE Karen_Words SET Pron = 'mu le ɣo' WHERE Word_ID = 1005;
UPDATE Karen_Words SET Pron = 'mu Pɔ Pa' WHERE Word_ID = 1006;
UPDATE Karen_Words SET Pron = 'mu Sa Kɔ ta ʔɔ' WHERE Word_ID = 1009;
UPDATE Karen_Words SET Pron = 'mu Tu Ka' WHERE Word_ID = 1010;
UPDATE Karen_Words SET Pron = 'mu ʒu' WHERE Word_ID = 1011;
UPDATE Karen_Words SET Pron = 'ɲa ga ma' WHERE Word_ID = 1014;
INSERT INTO Variants (Word_ID, VarPron) VALUES (1014, 'ɲa ʔa ma');
UPDATE Karen_Words SET Pron = 'pa Sɛ pa kə tɔ' WHERE Word_ID = 1019;
UPDATE Karen_Words SET Pron = 'pɛ ne' WHERE Word_ID = 1020;
INSERT INTO Variants (Word_ID, VarPron) VALUES (1020, 'lə ne');
UPDATE Karen_Words SET Pron = 'Pa li' WHERE Word_ID = 1022;
UPDATE Karen_Words SET Pron = 'Pɔ kɔ rɔ' WHERE Word_ID = 1024;
UPDATE Karen_Words SET Pron = 'Pɔ θa' WHERE Word_ID = 1025;
UPDATE Karen_Words SET Pron = 'Pjɛ ma' WHERE Word_ID = 1026;
UPDATE Karen_Words SET Pron = 'Pla fər' WHERE Word_ID = 1027;
UPDATE Karen_Words SET Pron = 'po mu Pɔ' WHERE Word_ID = 1031;
UPDATE Karen_Words SET Pron = 'po θu' WHERE Word_ID = 1033;
UPDATE Karen_Words SET Pron = 'sa Pi θa' WHERE Word_ID = 1035;
UPDATE Karen_Words SET Pron = 'Sa tɔ' WHERE Word_ID = 1036;
UPDATE Karen_Words SET Pron = 'Sɛ Ki' WHERE Word_ID = 1038;
UPDATE Karen_Words SET Pron = 'Si mu' WHERE Word_ID = 1039;
UPDATE Karen_Words SET Pron = 'Si Sa' WHERE Word_ID = 1040;
UPDATE Karen_Words SET Pron = 'si ri ʔəl' WHERE Word_ID = 1041;
UPDATE Karen_Words SET Pron = 'ta ki' WHERE Word_ID = 1044;
UPDATE Karen_Words SET Pron = 'ta ko mi' WHERE Word_ID = 1045;
UPDATE Karen_Words SET Pron = 'ta ko mu' WHERE Word_ID = 1046;
UPDATE Karen_Words SET Pron = 'ta nə ti' WHERE Word_ID = 1048;
UPDATE Karen_Words SET Pron = 'ta ny Ti' WHERE Word_ID = 1049;
UPDATE Karen_Words SET Pron = 'ta Po ta li' WHERE Word_ID = 1050;
UPDATE Karen_Words SET Pron = 'ta Sə kə tɔ' WHERE Word_ID = 1051;
UPDATE Karen_Words SET Pron = 'ta tɔ ta la' WHERE Word_ID = 1052;
UPDATE Karen_Words SET Pron = 'ta tə Ka Ka' WHERE Word_ID = 1053;
UPDATE Karen_Words SET Pron = 'ta tə nɔ' WHERE Word_ID = 1055;
UPDATE Karen_Words SET Pron = 'ta θa' WHERE Word_ID = 1060;
UPDATE Karen_Words SET Pron = 'ta θi kwa' WHERE Word_ID = 1061;
UPDATE Karen_Words SET Pron = 'tɔ Po' WHERE Word_ID = 1062;
UPDATE Karen_Words SET Pron = 'tə kɔ θa' WHERE Word_ID = 1063;
UPDATE Karen_Words SET Pron = 'tə Ka Ka ki' WHERE Word_ID = 1064;
UPDATE Karen_Words SET Pron = 'tə Ka ki' WHERE Word_ID = 1065;
UPDATE Karen_Words SET Pron = 'te ku' WHERE Word_ID = 1067;
UPDATE Karen_Words SET Pron = 'te ɲa' WHERE Word_ID = 1069;
UPDATE Karen_Words SET Pron = 'tə nɔ' WHERE Word_ID = 1070;
UPDATE Karen_Words SET Pron = 'tə ni ɲa ʔi' WHERE Word_ID = 1071;
UPDATE Karen_Words SET Pron = 'wi li' WHERE Word_ID = 1086;
UPDATE Karen_Words SET Pron = 'wi li' WHERE Word_ID = 1087;
UPDATE Karen_Words SET Pron = 'ʔa Kɔ Ti' WHERE Word_ID = 1088;
UPDATE Karen_Words SET Pron = 'ʔa la' WHERE Word_ID = 1089;
UPDATE Karen_Words SET Pron = 'ʔa lɛ ra' WHERE Word_ID = 1090;
UPDATE Karen_Words SET Pron = 'ʔa lo Ki' WHERE Word_ID = 1091;
UPDATE Karen_Words SET Pron = 'ʔa lo Ki' WHERE Word_ID = 1093;
UPDATE Karen_Words SET Pron = 'ʔa lu' WHERE Word_ID = 1094;
UPDATE Karen_Words SET Pron = 'ʔa me ɲa' WHERE Word_ID = 1095;
UPDATE Karen_Words SET Pron = 'ʔa na ri ba' WHERE Word_ID = 1096;
UPDATE Karen_Words SET Pron = 'ʔa pɔ' WHERE Word_ID = 1097;
UPDATE Karen_Words SET Pron = 'ʔa Pa mɛn' WHERE Word_ID = 1099;
UPDATE Karen_Words SET Pron = 'ʔa Pu' WHERE Word_ID = 1100;
UPDATE Karen_Words SET Pron = 'ʔa sə tɔ kli' WHERE Word_ID = 1101;
UPDATE Karen_Words SET Pron = 'ʔa Sə kə tɔ' WHERE Word_ID = 1102;
UPDATE Karen_Words SET Pron = 'ʔa tɔ' WHERE Word_ID = 1103;
UPDATE Karen_Words SET Pron = 'ʔa xə' WHERE Word_ID = 1105;
UPDATE Karen_Words SET Pron = 'ʔa θa ki' WHERE Word_ID = 1106;
UPDATE Karen_Words SET Pron = 'ʔɔ ɣɔ' WHERE Word_ID = 1108;
UPDATE Karen_Words SET Pron = 'ʔo tɔ' WHERE Word_ID = 1110;
UPDATE Karen_Words SET Pron = 'ʔo tɔ' WHERE Word_ID = 1110;
UPDATE Karen_Words SET Pron = 'θa Pwi tɛ lɛ' WHERE Word_ID = 1114;
UPDATE Karen_Words SET Pron = 'θa sa' WHERE Word_ID = 1116;
UPDATE Karen_Words SET Pron = 'θe kə ʃa' WHERE Word_ID = 1118;
UPDATE Karen_Words SET Pron = 'θə la' WHERE Word_ID = 1119;
UPDATE Karen_Words SET Pron = 'θə pa pɔ ti' WHERE Word_ID = 1120;
UPDATE Karen_Words SET Pron = 'θə pa Pɔ' WHERE Word_ID = 1121;
UPDATE Karen_Words SET Pron = 'θu tɔ' WHERE Word_ID = 1123;
UPDATE Karen_Words SET Pron = 'θwe kɔ' WHERE Word_ID = 1124;
UPDATE Karen_Words SET Pron = 'a ʁi' WHERE Word_ID = 1125;
UPDATE Karen_Words SET Pron = 'a θa Sʌ Sʌ' WHERE Word_ID = 1126;
UPDATE Karen_Words SET Pron = 'a θa Sʌ Sʌ' WHERE Word_ID = 1126;
UPDATE Karen_Words SET Pron = 'ko ʧʰwɔ kə bli' WHERE Word_ID = 1130;
UPDATE Karen_Words SET Pron = 'lɔ Ki' WHERE Word_ID = 1131;
UPDATE Karen_Words SET Pron = 'Po ʧi ʧi Po' WHERE Word_ID = 1133;
UPDATE Karen_Words SET Pron = 'a beʔ' WHERE Word_ID = 1139;
UPDATE Karen_Words SET Pron = 'a duʔ' WHERE Word_ID = 1141;
UPDATE Karen_Words SET Pron = 'a ka Pa' WHERE Word_ID = 1142;
UPDATE Karen_Words SET Pron = 'a kə su' WHERE Word_ID = 1143;
UPDATE Karen_Words SET Pron = 'a kə θa' WHERE Word_ID = 1144;
UPDATE Karen_Words SET Pron = 'a Ka' WHERE Word_ID = 1145;
UPDATE Karen_Words SET Pron = 'a Ka' WHERE Word_ID = 1146;
UPDATE Karen_Words SET Pron = 'a Ko dʊ' WHERE Word_ID = 1147;
UPDATE Karen_Words SET Pron = 'a ko' WHERE Word_ID = 1149;
UPDATE Karen_Words SET Pron = 'a Pɔ Ko' WHERE Word_ID = 1155;
UPDATE Karen_Words SET Pron = 'a Pɔ Koː' WHERE Word_ID = 1156;
UPDATE Karen_Words SET Pron = 'a Pɔ la' WHERE Word_ID = 1157;
UPDATE Karen_Words SET Pron = 'a Po' WHERE Word_ID = 1158;
UPDATE Karen_Words SET Pron = 'a Pu' WHERE Word_ID = 1159;
UPDATE Karen_Words SET Pron = 'a pu kwi' WHERE Word_ID = 1160;
UPDATE Karen_Words SET Pron = 'a pu kwi' WHERE Word_ID = 1161;
UPDATE Karen_Words SET Pron = 'a ʁe' WHERE Word_ID = 1162;
UPDATE Karen_Words SET Pron = 'a ʁe' WHERE Word_ID = 1163;
UPDATE Karen_Words SET Pron = 'a ʁe' WHERE Word_ID = 1164;
UPDATE Karen_Words SET Pron = 'a wa' WHERE Word_ID = 1165;
UPDATE Karen_Words SET Pron = 'a wa' WHERE Word_ID = 1166;
UPDATE Karen_Words SET Pron = 'a wɛ' WHERE Word_ID = 1168;
UPDATE Karen_Words SET Pron = 'a wɛ po Kwa' WHERE Word_ID = 1169;
UPDATE Karen_Words SET Pron = 'a wɛ θi' WHERE Word_ID = 1170;
UPDATE Karen_Words SET Pron = 'a xa' WHERE Word_ID = 1171;
UPDATE Karen_Words SET Pron = 'a θa' WHERE Word_ID = 1172;
UPDATE Karen_Words SET Pron = 'a θa' WHERE Word_ID = 1173;
UPDATE Karen_Words SET Pron = 'a θa ke' WHERE Word_ID = 1174;
UPDATE Karen_Words SET Pron = 'a θa ʔʊ' WHERE Word_ID = 1175;
UPDATE Karen_Words SET Pron = 'a θi θo' WHERE Word_ID = 1176;
UPDATE Karen_Words SET Pron = 'ba ʔəː' WHERE Word_ID = 1178;
UPDATE Karen_Words SET Pron = 'ba θa' WHERE Word_ID = 1180;
UPDATE Karen_Words SET Pron = 'bɔ lɛ' WHERE Word_ID = 1181;
UPDATE Karen_Words SET Pron = 'bɔ lɛ Klo' WHERE Word_ID = 1182;
UPDATE Karen_Words SET Pron = 'bɔ lɛ ni' WHERE Word_ID = 1183;
UPDATE Karen_Words SET Pron = 'bɔ θo' WHERE Word_ID = 1184;
UPDATE Karen_Words SET Pron = 'bu dɔ' WHERE Word_ID = 1187;
UPDATE Karen_Words SET Pron = 'bu kɪ θa' WHERE Word_ID = 1188;
UPDATE Karen_Words SET Pron = 'bwa po mu Po' WHERE Word_ID = 1191;
UPDATE Karen_Words SET Pron = 'bwa ta ɰa' WHERE Word_ID = 1192;
UPDATE Karen_Words SET Pron = 'ɗɔ də ʔɪ ba' WHERE Word_ID = 1198;
UPDATE Karen_Words SET Pron = 'ɗɔː klɔ lɔ ɾa' WHERE Word_ID = 1200;
UPDATE Karen_Words SET Pron = 'ɗɔː ʃɔ lɔ ɾa' WHERE Word_ID = 1201;
UPDATE Karen_Words SET Pron = 'ɗɔː ʃɔ lɔ ɾa' WHERE Word_ID = 1202;
UPDATE Karen_Words SET Pron = 'dɔː du' WHERE Word_ID = 1203;
UPDATE Karen_Words SET Pron = 'dɔ beʔ' WHERE Word_ID = 1204;
UPDATE Karen_Words SET Pron = 'dɔ Pu ʔɛ mʊ' WHERE Word_ID = 1206;
UPDATE Karen_Words SET Pron = 'deː θə Pʌ' WHERE Word_ID = 1208;
UPDATE Karen_Words SET Pron = 'de Po' WHERE Word_ID = 1212;
UPDATE Karen_Words SET Pron = 'də Sʊ ba' WHERE Word_ID = 1213;
UPDATE Karen_Words SET Pron = 'di θa' WHERE Word_ID = 1216;
UPDATE Karen_Words SET Pron = 'do lɛ' WHERE Word_ID = 1218;
UPDATE Karen_Words SET Pron = 'gɔ la wa' WHERE Word_ID = 1230;
UPDATE Karen_Words SET Pron = 'gɔ la wa' WHERE Word_ID = 1230;
UPDATE Karen_Words SET Pron = 'gɔ la wa ko' WHERE Word_ID = 1231;
UPDATE Karen_Words SET Pron = 'gə mẽ si so' WHERE Word_ID = 1232;
UPDATE Karen_Words SET Pron = 'ha Su' WHERE Word_ID = 1239;
UPDATE Karen_Words SET Pron = 'ha Tɔ' WHERE Word_ID = 1240;
UPDATE Karen_Words SET Pron = 'hɛ xɔ' WHERE Word_ID = 1244;
UPDATE Karen_Words SET Pron = 'hi Tɔ' WHERE Word_ID = 1247;
UPDATE Karen_Words SET Pron = 'kă laː' WHERE Word_ID = 1257;
UPDATE Karen_Words SET Pron = 'ka Pɔː' WHERE Word_ID = 1258;
UPDATE Karen_Words SET Pron = 'ka Pi' WHERE Word_ID = 1259;
UPDATE Karen_Words SET Pron = 'ka θe' WHERE Word_ID = 1260;
UPDATE Karen_Words SET Pron = 'kə le ha' WHERE Word_ID = 1267;
UPDATE Karen_Words SET Pron = 'kə le suː' WHERE Word_ID = 1268;
UPDATE Karen_Words SET Pron = 'kə mʊ̃ se' WHERE Word_ID = 1269;
UPDATE Karen_Words SET Pron = 'kə mʊ̃ sɪ' WHERE Word_ID = 1270;
UPDATE Karen_Words SET Pron = 'ke ʔi' WHERE Word_ID = 1274;
UPDATE Karen_Words SET Pron = 'Ke le' WHERE Word_ID = 1276;
UPDATE Karen_Words SET Pron = 'Ke ʔi' WHERE Word_ID = 1277;
UPDATE Karen_Words SET Pron = 'Klo bɔ lɛ' WHERE Word_ID = 1280;
UPDATE Karen_Words SET Pron = 'ki Se' WHERE Word_ID = 1282;
UPDATE Karen_Words SET Pron = 'ki Se' WHERE Word_ID = 1283;
UPDATE Karen_Words SET Pron = 'klɒ də Pa ne' WHERE Word_ID = 1285;
UPDATE Karen_Words SET Pron = 'klɔ lɔ ta' WHERE Word_ID = 1289;
UPDATE Karen_Words SET Pron = 'ko ə kiː' WHERE Word_ID = 1296;
UPDATE Karen_Words SET Pron = 'ko nã θaː' WHERE Word_ID = 1297;
UPDATE Karen_Words SET Pron = 'ko po θaː' WHERE Word_ID = 1298;
UPDATE Karen_Words SET Pron = 'ko xɔ θaː' WHERE Word_ID = 1301;
UPDATE Karen_Words SET Pron = 'ko Ke' WHERE Word_ID = 1302;
UPDATE Karen_Words SET Pron = 'ko Ke a keː' WHERE Word_ID = 1303;
UPDATE Karen_Words SET Pron = 'ko mu ̃Pwa' WHERE Word_ID = 1304;
UPDATE Karen_Words SET Pron = 'ko tə lo' WHERE Word_ID = 1305;
UPDATE Karen_Words SET Pron = 'ko ʔɛ ʃa' WHERE Word_ID = 1307;
UPDATE Karen_Words SET Pron = 'kʌ bɔ ju' WHERE Word_ID = 1310;
UPDATE Karen_Words SET Pron = 'kʌ θu Ti' WHERE Word_ID = 1311;
UPDATE Karen_Words SET Pron = 'kwa ka te ka to' WHERE Word_ID = 1314;
UPDATE Karen_Words SET Pron = 'la he' WHERE Word_ID = 1318;
UPDATE Karen_Words SET Pron = 'la pa Ti nɔ te' WHERE Word_ID = 1319;
UPDATE Karen_Words SET Pron = 'la Pa' WHERE Word_ID = 1320;
UPDATE Karen_Words SET Pron = 'lɔ Kɔː' WHERE Word_ID = 1325;
UPDATE Karen_Words SET Pron = 'lɔ ɰa' WHERE Word_ID = 1327;
UPDATE Karen_Words SET Pron = 'lɔ Sɔ' WHERE Word_ID = 1328;
UPDATE Karen_Words SET Pron = 'lɔ tɛ Su' WHERE Word_ID = 1329;
UPDATE Karen_Words SET Pron = 'le Su' WHERE Word_ID = 1331;
UPDATE Karen_Words SET Pron = 'lə Tɔ Kɔ' WHERE Word_ID = 1332;
UPDATE Karen_Words SET Pron = 'lo baː' WHERE Word_ID = 1334;
UPDATE Karen_Words SET Pron = 'lu i pu tə pu' WHERE Word_ID = 1335;
UPDATE Karen_Words SET Pron = 'lu tə kʊ' WHERE Word_ID = 1336;
UPDATE Karen_Words SET Pron = 'ma ha Kʌ' WHERE Word_ID = 1341;
UPDATE Karen_Words SET Pron = 'ma ka lɔ kwɪ' WHERE Word_ID = 1342;
UPDATE Karen_Words SET Pron = 'ma ka ʃɔ ɾaː' WHERE Word_ID = 1343;
UPDATE Karen_Words SET Pron = 'ma ɾa' WHERE Word_ID = 1345;
UPDATE Karen_Words SET Pron = 'ɰɔ ɰɔ' WHERE Word_ID = 1346;
UPDATE Karen_Words SET Pron = 'mə̃ nũ' WHERE Word_ID = 1351;
UPDATE Karen_Words SET Pron = 'ɰɛ kə li' WHERE Word_ID = 1355;
UPDATE Karen_Words SET Pron = 'mu ko' WHERE Word_ID = 1359;
UPDATE Karen_Words SET Pron = 'mu ̃ko ʧu' WHERE Word_ID = 1360;
UPDATE Karen_Words SET Pron = 'mu na' WHERE Word_ID = 1361;
UPDATE Karen_Words SET Pron = 'nɔ te' WHERE Word_ID = 1366;
UPDATE Karen_Words SET Pron = 'nɔ te ɔ me' WHERE Word_ID = 1367;
UPDATE Karen_Words SET Pron = 'nɔ te kə θu Ti' WHERE Word_ID = 1368;
UPDATE Karen_Words SET Pron = 'nɔ te Sɔ ta' WHERE Word_ID = 1369;
UPDATE Karen_Words SET Pron = 'nɔ̃ tə ʧɛː' WHERE Word_ID = 1370;
UPDATE Karen_Words SET Pron = 'nɔ̃ θu le' WHERE Word_ID = 1372;
UPDATE Karen_Words SET Pron = 'ne θu' WHERE Word_ID = 1374;
UPDATE Karen_Words SET Pron = 'o bu' WHERE Word_ID = 1378;
UPDATE Karen_Words SET Pron = 'pə lɒ θe pa θe' WHERE Word_ID = 1385;
UPDATE Karen_Words SET Pron = 'pɛ lɔ ke' WHERE Word_ID = 1387;
UPDATE Karen_Words SET Pron = 'Pa θe mũ' WHERE Word_ID = 1391;
UPDATE Karen_Words SET Pron = 'Pa dɔ ɲã' WHERE Word_ID = 1392;
UPDATE Karen_Words SET Pron = 'Pa do' WHERE Word_ID = 1393;
UPDATE Karen_Words SET Pron = 'Pa kə bu' WHERE Word_ID = 1396;
UPDATE Karen_Words SET Pron = 'Pɔ Ko' WHERE Word_ID = 1399;
UPDATE Karen_Words SET Pron = 'Pɛ lɛ' WHERE Word_ID = 1400;
UPDATE Karen_Words SET Pron = 'Pɛ ne' WHERE Word_ID = 1401;
UPDATE Karen_Words SET Pron = 'Po θa' WHERE Word_ID = 1406;
UPDATE Karen_Words SET Pron = 'Pu daː' WHERE Word_ID = 1411;
UPDATE Karen_Words SET Pron = 'Pu ne' WHERE Word_ID = 1413;
UPDATE Karen_Words SET Pron = 'pɪ θa' WHERE Word_ID = 1414;
UPDATE Karen_Words SET Pron = 'pwa du le Po' WHERE Word_ID = 1418;
UPDATE Karen_Words SET Pron = 'pwo Ti' WHERE Word_ID = 1422;
UPDATE Karen_Words SET Pron = 'rə ʃa' WHERE Word_ID = 1423;
UPDATE Karen_Words SET Pron = 'ʃɔ lɔ ta' WHERE Word_ID = 1427;
UPDATE Karen_Words SET Pron = 'sɔ nɔ koʔ' WHERE Word_ID = 1428;
UPDATE Karen_Words SET Pron = 'sɔ pɔ' WHERE Word_ID = 1429;
UPDATE Karen_Words SET Pron = 'sɛ dɔ lɛ' WHERE Word_ID = 1430;
UPDATE Karen_Words SET Pron = 'Sa ko' WHERE Word_ID = 1431;
UPDATE Karen_Words SET Pron = 'Sa ko Pa' WHERE Word_ID = 1432;
UPDATE Karen_Words SET Pron = 'Sɔ kə peː' WHERE Word_ID = 1434;
UPDATE Karen_Words SET Pron = 'Sɔ nɔ̃ ko' WHERE Word_ID = 1435;
UPDATE Karen_Words SET Pron = 'Sɔ Tɔ Ta' WHERE Word_ID = 1436;
UPDATE Karen_Words SET Pron = 'Su Pɔ lɔ tɛ Su' WHERE Word_ID = 1438;
UPDATE Karen_Words SET Pron = 'su bi' WHERE Word_ID = 1441;
UPDATE Karen_Words SET Pron = 'taː Tə' WHERE Word_ID = 1445;
UPDATE Karen_Words SET Pron = 'taː Tə lɔ Kɔ' WHERE Word_ID = 1446;
UPDATE Karen_Words SET Pron = 'ta dɔ lɛ sɛ' WHERE Word_ID = 1447;
UPDATE Karen_Words SET Pron = 'ta do ta la' WHERE Word_ID = 1448;
UPDATE Karen_Words SET Pron = 'ta ɣi' WHERE Word_ID = 1449;
UPDATE Karen_Words SET Pron = 'ta ka mũ' WHERE Word_ID = 1450;
UPDATE Karen_Words SET Pron = 'ta ke ɲa' WHERE Word_ID = 1451;
UPDATE Karen_Words SET Pron = 'ta lɔ' WHERE Word_ID = 1452;
UPDATE Karen_Words SET Pron = 'ta le ha' WHERE Word_ID = 1453;
UPDATE Karen_Words SET Pron = 'ta lɛ ha ɾa a lɔ' WHERE Word_ID = 1455;
UPDATE Karen_Words SET Pron = 'ta mã' WHERE Word_ID = 1458;
UPDATE Karen_Words SET Pron = 'ta nĩ ʔeː' WHERE Word_ID = 1459;
UPDATE Karen_Words SET Pron = 'ta nu Ti' WHERE Word_ID = 1460;
UPDATE Karen_Words SET Pron = 'ta nu Ti də pə lɔ' WHERE Word_ID = 1462;
UPDATE Karen_Words SET Pron = 'ta nu Ti ʧĭ' WHERE Word_ID = 1463;
UPDATE Karen_Words SET Pron = 'ta nu ʧi tə koː' WHERE Word_ID = 1464;
UPDATE Karen_Words SET Pron = 'ta Pɔ ʔɔ lɔ' WHERE Word_ID = 1465;
UPDATE Karen_Words SET Pron = 'ta Po mɛ̃' WHERE Word_ID = 1466;
UPDATE Karen_Words SET Pron = 'ta Po xa' WHERE Word_ID = 1467;
UPDATE Karen_Words SET Pron = 'ta ʀo' WHERE Word_ID = 1469;
UPDATE Karen_Words SET Pron = 'ta Sa hiʔ' WHERE Word_ID = 1470;
UPDATE Karen_Words SET Pron = 'ta ta mi mi' WHERE Word_ID = 1471;
UPDATE Karen_Words SET Pron = 'ta ʧu' WHERE Word_ID = 1473;
UPDATE Karen_Words SET Pron = 'ta xe θaː' WHERE Word_ID = 1474;
UPDATE Karen_Words SET Pron = 'ta ʔaː duʔ' WHERE Word_ID = 1475;
UPDATE Karen_Words SET Pron = 'ta ʔɔ ta ʔɔ' WHERE Word_ID = 1477;
UPDATE Karen_Words SET Pron = 'ta θe ʔa lɔ' WHERE Word_ID = 1479;
UPDATE Karen_Words SET Pron = 'ta θə da' WHERE Word_ID = 1480;
UPDATE Karen_Words SET Pron = 'ta θə da ʔa lɔ' WHERE Word_ID = 1481;
UPDATE Karen_Words SET Pron = 'ta θe lɔ Kɔ ʔa lɔ' WHERE Word_ID = 1482;
UPDATE Karen_Words SET Pron = 'ta θu ta θa' WHERE Word_ID = 1483;
UPDATE Karen_Words SET Pron = 'ta θu ta θa ə ɣa' WHERE Word_ID = 1484;
UPDATE Karen_Words SET Pron = 'tɔ Pɔ di baː' WHERE Word_ID = 1486;
UPDATE Karen_Words SET Pron = 'tɔ wa' WHERE Word_ID = 1487;
UPDATE Karen_Words SET Pron = 'tə di tə ka' WHERE Word_ID = 1490;
UPDATE Karen_Words SET Pron = 'tə ko' WHERE Word_ID = 1491;
UPDATE Karen_Words SET Pron = 'tə ʔo baː' WHERE Word_ID = 1494;
UPDATE Karen_Words SET Pron = 'te θɔ Kɔ' WHERE Word_ID = 1495;
UPDATE Karen_Words SET Pron = 'Tɔ ba ɗɔː' WHERE Word_ID = 1500;
UPDATE Karen_Words SET Pron = 'Tɔ bo' WHERE Word_ID = 1501;
UPDATE Karen_Words SET Pron = 'Tɔ po ɣa' WHERE Word_ID = 1502;
UPDATE Karen_Words SET Pron = 'Ti ka la' WHERE Word_ID = 1507;
UPDATE Karen_Words SET Pron = 'Ti Ki' WHERE Word_ID = 1508;
UPDATE Karen_Words SET Pron = 'Ti nẽ' WHERE Word_ID = 1516;
UPDATE Karen_Words SET Pron = 'Ti Ta' WHERE Word_ID = 1517;
UPDATE Karen_Words SET Pron = 'To de' WHERE Word_ID = 1521;
UPDATE Karen_Words SET Pron = 'To de' WHERE Word_ID = 1522;
UPDATE Karen_Words SET Pron = 'To de ɲa' WHERE Word_ID = 1523;
UPDATE Karen_Words SET Pron = 'To de ʔa diʔ' WHERE Word_ID = 1524;
UPDATE Karen_Words SET Pron = 'Two de' WHERE Word_ID = 1528;
UPDATE Karen_Words SET Pron = 'tɹe lo' WHERE Word_ID = 1532;
UPDATE Karen_Words SET Pron = 'ʧɛ θu' WHERE Word_ID = 1535;
UPDATE Karen_Words SET Pron = 'ʧʰa Pɔ kɔ Po' WHERE Word_ID = 1538;
UPDATE Karen_Words SET Pron = 'ʧʰɔ dɛ' WHERE Word_ID = 1541;
UPDATE Karen_Words SET Pron = 'ʧʰɔ di' WHERE Word_ID = 1542;
UPDATE Karen_Words SET Pron = 'ʧʰɔ hi' WHERE Word_ID = 1543;
UPDATE Karen_Words SET Pron = 'ʧʰɔ ka rʌ' WHERE Word_ID = 1544;
UPDATE Karen_Words SET Pron = 'ʧʰɔ xa' WHERE Word_ID = 1545;
UPDATE Karen_Words SET Pron = 'ʧi ʧi Po' WHERE Word_ID = 1546;
UPDATE Karen_Words SET Pron = 'tu su' WHERE Word_ID = 1549;
UPDATE Karen_Words SET Pron = 'tʌ kə ru' WHERE Word_ID = 1550;
UPDATE Karen_Words SET Pron = 'wu ɣi' WHERE Word_ID = 1557;
UPDATE Karen_Words SET Pron = 'xɔ de' WHERE Word_ID = 1559;
UPDATE Karen_Words SET Pron = 'xɔ la' WHERE Word_ID = 1560;
UPDATE Karen_Words SET Pron = 'xɔ θaː' WHERE Word_ID = 1561;
UPDATE Karen_Words SET Pron = 'ʔa ɓɔ' WHERE Word_ID = 1567;
UPDATE Karen_Words SET Pron = 'ʔa ɓɔː' WHERE Word_ID = 1568;
UPDATE Karen_Words SET Pron = 'ʔa ka' WHERE Word_ID = 1569;
UPDATE Karen_Words SET Pron = 'ʔa lɔː' WHERE Word_ID = 1570;
UPDATE Karen_Words SET Pron = 'ʔa lu Tɨ' WHERE Word_ID = 1571;
UPDATE Karen_Words SET Pron = 'ʔa ʔɪʔ' WHERE Word_ID = 1572;
UPDATE Karen_Words SET Pron = 'ʔɔ lə' WHERE Word_ID = 1574;
UPDATE Karen_Words SET Pron = 'ʔɛ dɔ' WHERE Word_ID = 1577;
UPDATE Karen_Words SET Pron = 'ʔɨ Tɔ Ta' WHERE Word_ID = 1580;
UPDATE Karen_Words SET Pron = 'ʔi θa' WHERE Word_ID = 1582;
UPDATE Karen_Words SET Pron = 'ʔi θa ha' WHERE Word_ID = 1583;
UPDATE Karen_Words SET Pron = 'ʔi θa ʧa' WHERE Word_ID = 1584;
UPDATE Karen_Words SET Pron = 'ʔo kɔ' WHERE Word_ID = 1586;
UPDATE Karen_Words SET Pron = 'θa baː wɔ ti' WHERE Word_ID = 1588;
UPDATE Karen_Words SET Pron = 'θa dɔ' WHERE Word_ID = 1590;
UPDATE Karen_Words SET Pron = 'θa nu Ti lɔ θə kaː' WHERE Word_ID = 1593;
UPDATE Karen_Words SET Pron = 'θa nu ʧi lɔ θa kaː a ke Po' WHERE Word_ID = 1594;
UPDATE Karen_Words SET Pron = 'θe pu tə pu' WHERE Word_ID = 1599;
UPDATE Karen_Words SET Pron = 'θi θoː' WHERE Word_ID = 1600;
UPDATE Karen_Words SET Pron = 'a we' WHERE Word_ID = 1617;
UPDATE Karen_Words SET Pron = 'a we po kwa' WHERE Word_ID = 1618;
UPDATE Karen_Words SET Pron = 'a we po mu' WHERE Word_ID = 1619;
UPDATE Karen_Words SET Pron = 'a we θi' WHERE Word_ID = 1620;
UPDATE Karen_Words SET Pron = 'mu sa' WHERE Word_ID = 1681;
UPDATE Karen_Words SET Pron = 'nə θu' WHERE Word_ID = 1685;
UPDATE Karen_Words SET Pron = 'a ka pe le' WHERE Word_ID = 1742;
UPDATE Karen_Words SET Pron = 'a we ji' WHERE Word_ID = 1744;
UPDATE Karen_Words SET Pron = 'a we po mu' WHERE Word_ID = 1752;
UPDATE Karen_Words SET Pron = 'ba me nu le' WHERE Word_ID = 1754;
UPDATE Karen_Words SET Pron = 'bo le' WHERE Word_ID = 1758;
UPDATE Karen_Words SET Pron = 'bo tɔ' WHERE Word_ID = 1760;
UPDATE Karen_Words SET Pron = 'da lu' WHERE Word_ID = 1762;
UPDATE Karen_Words SET Pron = 'de ni jai' WHERE Word_ID = 1763;
UPDATE Karen_Words SET Pron = 'de xi' WHERE Word_ID = 1764;
UPDATE Karen_Words SET Pron = 'do ka pu' WHERE Word_ID = 1769;
UPDATE Karen_Words SET Pron = 'ə ne' WHERE Word_ID = 1772;
UPDATE Karen_Words SET Pron = 'ga ha' WHERE Word_ID = 1774;
UPDATE Karen_Words SET Pron = 'ɤi do' WHERE Word_ID = 1776;
UPDATE Karen_Words SET Pron = 'gi lo lə' WHERE Word_ID = 1777;
UPDATE Karen_Words SET Pron = 'he du' WHERE Word_ID = 1780;
UPDATE Karen_Words SET Pron = 'he ki' WHERE Word_ID = 1781;
UPDATE Karen_Words SET Pron = 'hɛ lo' WHERE Word_ID = 1782;
UPDATE Karen_Words SET Pron = 'hi po ha po' WHERE Word_ID = 1783;
UPDATE Karen_Words SET Pron = 'ka da ki' WHERE Word_ID = 1789;
UPDATE Karen_Words SET Pron = 'kɔ te' WHERE Word_ID = 1792;
UPDATE Karen_Words SET Pron = 'kə θi' WHERE Word_ID = 1793;
UPDATE Karen_Words SET Pron = 'ko bo ju' WHERE Word_ID = 1794;
UPDATE Karen_Words SET Pron = 'le jə' WHERE Word_ID = 1797;
UPDATE Karen_Words SET Pron = 'lu ba' WHERE Word_ID = 1804;
UPDATE Karen_Words SET Pron = 'ma ha te ni' WHERE Word_ID = 1810;
UPDATE Karen_Words SET Pron = 'me nu le' WHERE Word_ID = 1813;
UPDATE Karen_Words SET Pron = 'mu ɣa' WHERE Word_ID = 1816;
UPDATE Karen_Words SET Pron = 'mu ɣa' WHERE Word_ID = 1816;
UPDATE Karen_Words SET Pron = 'mu ko pa' WHERE Word_ID = 1819;
UPDATE Karen_Words SET Pron = 'mu ko su' WHERE Word_ID = 1821;
UPDATE Karen_Words SET Pron = 'mu ta le' WHERE Word_ID = 1825;
UPDATE Karen_Words SET Pron = 'nu lə' WHERE Word_ID = 1833;
UPDATE Karen_Words SET Pron = 'o do' WHERE Word_ID = 1834;
UPDATE Karen_Words SET Pron = 'o do' WHERE Word_ID = 1834;
UPDATE Karen_Words SET Pron = 'Po θa' WHERE Word_ID = 1840;
UPDATE Karen_Words SET Pron = 'pi pu' WHERE Word_ID = 1844;
UPDATE Karen_Words SET Pron = 'po Ti' WHERE Word_ID = 1849;
UPDATE Karen_Words SET Pron = 'po wej' WHERE Word_ID = 1850;
UPDATE Karen_Words SET Pron = 'po θa si' WHERE Word_ID = 1853;
UPDATE Karen_Words SET Pron = 'pu ti' WHERE Word_ID = 1855;
UPDATE Karen_Words SET Pron = 'Sə tɔ' WHERE Word_ID = 1861;
UPDATE Karen_Words SET Pron = 'so tɔ' WHERE Word_ID = 1867;
UPDATE Karen_Words SET Pron = 'ta bo' WHERE Word_ID = 1869;
UPDATE Karen_Words SET Pron = 'ta lo pe le' WHERE Word_ID = 1873;
UPDATE Karen_Words SET Pron = 'ta po' WHERE Word_ID = 1875;
UPDATE Karen_Words SET Pron = 'te le' WHERE Word_ID = 1879;
UPDATE Karen_Words SET Pron = 'to lə' WHERE Word_ID = 1893;
UPDATE Karen_Words SET Pron = 'to lə' WHERE Word_ID = 1894;
UPDATE Karen_Words SET Pron = 'to pu we' WHERE Word_ID = 1895;
UPDATE Karen_Words SET Pron = 'to pu we mu' WHERE Word_ID = 1897;
UPDATE Karen_Words SET Pron = 'xa ko:' WHERE Word_ID = 1901;
UPDATE Karen_Words SET Pron = 'θa da' WHERE Word_ID = 1903;
UPDATE Karen_Words SET Pron = 'θa sa' WHERE Word_ID = 1905;
UPDATE Karen_Words SET Pron = 'θi na' WHERE Word_ID = 1909;
UPDATE Karen_Words SET Pron = 'a me ri ka Po' WHERE Word_ID = 1920;
UPDATE Karen_Words SET Pron = 'a we' WHERE Word_ID = 1921;
UPDATE Karen_Words SET Pron = 'a we po kwa' WHERE Word_ID = 1922;
UPDATE Karen_Words SET Pron = 'a we po mu' WHERE Word_ID = 1923;
UPDATE Karen_Words SET Pron = 'ɓo mu' WHERE Word_ID = 1926;
UPDATE Karen_Words SET Pron = 'ɓra xo Po' WHERE Word_ID = 1931;
UPDATE Karen_Words SET Pron = 'ɣwi pa Tu kə Pa' WHERE Word_ID = 1934;
UPDATE Karen_Words SET Pron = 'ha ʥi' WHERE Word_ID = 1936;
UPDATE Karen_Words SET Pron = 'ha ʥi' WHERE Word_ID = 1936;
UPDATE Karen_Words SET Pron = 'ha Ka ʔo ta' WHERE Word_ID = 1937;
UPDATE Karen_Words SET Pron = 'ha xu ʔo ta' WHERE Word_ID = 1938;
UPDATE Karen_Words SET Pron = 'he tu' WHERE Word_ID = 1941;
UPDATE Karen_Words SET Pron = 'i Tə ne' WHERE Word_ID = 1943;
UPDATE Karen_Words SET Pron = 'ʝi to' WHERE Word_ID = 1945;
UPDATE Karen_Words SET Pron = 'ʝo Ko' WHERE Word_ID = 1948;
UPDATE Karen_Words SET Pron = 'kə Pu' WHERE Word_ID = 1950;
UPDATE Karen_Words SET Pron = 'kə sa' WHERE Word_ID = 1952;
UPDATE Karen_Words SET Pron = 'kə sə' WHERE Word_ID = 1953;
UPDATE Karen_Words SET Pron = 'Ke lə' WHERE Word_ID = 1956;
UPDATE Karen_Words SET Pron = 'Ke se' WHERE Word_ID = 1957;
UPDATE Karen_Words SET Pron = 'Klo ku' WHERE Word_ID = 1962;
UPDATE Karen_Words SET Pron = 'Ko ka' WHERE Word_ID = 1964;
UPDATE Karen_Words SET Pron = 'Ko pə jo' WHERE Word_ID = 1965;
UPDATE Karen_Words SET Pron = 'Ko ʧi no' WHERE Word_ID = 1968;
UPDATE Karen_Words SET Pron = 'ko se' WHERE Word_ID = 1976;
UPDATE Karen_Words SET Pron = 'kʌ Ko Ki' WHERE Word_ID = 1978;
UPDATE Karen_Words SET Pron = 'li mu' WHERE Word_ID = 1999;
UPDATE Karen_Words SET Pron = 'lo pa ʔə' WHERE Word_ID = 2002;
UPDATE Karen_Words SET Pron = 'ma mu Tʌ' WHERE Word_ID = 2008;
UPDATE Karen_Words SET Pron = 'ma tə lo θa' WHERE Word_ID = 2009;
UPDATE Karen_Words SET Pron = 'ma θi' WHERE Word_ID = 2010;
UPDATE Karen_Words SET Pron = 'mɪ ni' WHERE Word_ID = 2012;
UPDATE Karen_Words SET Pron = 'mɪ ni' WHERE Word_ID = 2012;
UPDATE Karen_Words SET Pron = 'mo pa' WHERE Word_ID = 2014;
UPDATE Karen_Words SET Pron = 'mu Ko' WHERE Word_ID = 2015;
UPDATE Karen_Words SET Pron = 'mu Ko' WHERE Word_ID = 2015;
UPDATE Karen_Words SET Pron = 'mu la' WHERE Word_ID = 2016;
UPDATE Karen_Words SET Pron = 'mu ʧa Ko' WHERE Word_ID = 2017;
UPDATE Karen_Words SET Pron = 'mu To Ka' WHERE Word_ID = 2018;
UPDATE Karen_Words SET Pron = 'na ɣi' WHERE Word_ID = 2020;
UPDATE Karen_Words SET Pron = 'ɲa pi' WHERE Word_ID = 2021;
UPDATE Karen_Words SET Pron = 'ɲa pi' WHERE Word_ID = 2021;
UPDATE Karen_Words SET Pron = 'ɲa po' WHERE Word_ID = 2022;
UPDATE Karen_Words SET Pron = 'ni pal' WHERE Word_ID = 2027;
UPDATE Karen_Words SET Pron = 'no Pa mu' WHERE Word_ID = 2030;
UPDATE Karen_Words SET Pron = 'no θo le' WHERE Word_ID = 2031;
UPDATE Karen_Words SET Pron = 'pa ha to' WHERE Word_ID = 2033;
UPDATE Karen_Words SET Pron = 'pa ko pa Ke' WHERE Word_ID = 2034;
UPDATE Karen_Words SET Pron = 'pa ma θa' WHERE Word_ID = 2035;
UPDATE Karen_Words SET Pron = 'pa so' WHERE Word_ID = 2036;
UPDATE Karen_Words SET Pron = 'pa θa' WHERE Word_ID = 2037;
UPDATE Karen_Words SET Pron = 'Pa li ma' WHERE Word_ID = 2040;
UPDATE Karen_Words SET Pron = 'Pa To' WHERE Word_ID = 2041;
UPDATE Karen_Words SET Pron = 'Pi Pa to' WHERE Word_ID = 2045;
UPDATE Karen_Words SET Pron = 'Po θe sa' WHERE Word_ID = 2049;
UPDATE Karen_Words SET Pron = 'Pu Pa to' WHERE Word_ID = 2052;
UPDATE Karen_Words SET Pron = 'po to' WHERE Word_ID = 2061;
UPDATE Karen_Words SET Pron = 'pwa kə ɲo Po' WHERE Word_ID = 2064;
UPDATE Karen_Words SET Pron = 'pwa kə ɲo Po' WHERE Word_ID = 2064;
UPDATE Karen_Words SET Pron = 'pwa θo Ka Po' WHERE Word_ID = 2066;
UPDATE Karen_Words SET Pron = 'sa Tu lə' WHERE Word_ID = 2068;
UPDATE Karen_Words SET Pron = 'sə ɗo ne' WHERE Word_ID = 2069;
UPDATE Karen_Words SET Pron = 'se Ka' WHERE Word_ID = 2070;
UPDATE Karen_Words SET Pron = 'se Ka' WHERE Word_ID = 2070;
UPDATE Karen_Words SET Pron = 'se Ka' WHERE Word_ID = 2071;
UPDATE Karen_Words SET Pron = 'sə mu la' WHERE Word_ID = 2072;
UPDATE Karen_Words SET Pron = 'sə mu la' WHERE Word_ID = 2072;
UPDATE Karen_Words SET Pron = 'Sa Po ko Po' WHERE Word_ID = 2075;
UPDATE Karen_Words SET Pron = 'so kə mo' WHERE Word_ID = 2082;
UPDATE Karen_Words SET Pron = 'so nə Ku' WHERE Word_ID = 2083;
UPDATE Karen_Words SET Pron = 'so Pa' WHERE Word_ID = 2084;
UPDATE Karen_Words SET Pron = 'so Pa po mu' WHERE Word_ID = 2086;
UPDATE Karen_Words SET Pron = 'su ʧo' WHERE Word_ID = 2088;
UPDATE Karen_Words SET Pron = 'ta hi' WHERE Word_ID = 2090;
UPDATE Karen_Words SET Pron = 'ta Po θe sa' WHERE Word_ID = 2091;
UPDATE Karen_Words SET Pron = 'ta ʔo Po' WHERE Word_ID = 2093;
UPDATE Karen_Words SET Pron = 'ta θo ta θo' WHERE Word_ID = 2094;
UPDATE Karen_Words SET Pron = 'ta θu Ku θa Ku' WHERE Word_ID = 2095;
UPDATE Karen_Words SET Pron = 'tə kã po' WHERE Word_ID = 2096;
UPDATE Karen_Words SET Pron = 'te mu' WHERE Word_ID = 2102;
UPDATE Karen_Words SET Pron = 'tə ni' WHERE Word_ID = 2103;
UPDATE Karen_Words SET Pron = 'tə ni' WHERE Word_ID = 2103;
UPDATE Karen_Words SET Pron = 'te Po' WHERE Word_ID = 2104;
UPDATE Karen_Words SET Pron = 'tə ru Ko' WHERE Word_ID = 2105;
UPDATE Karen_Words SET Pron = 'Ta kə ma' WHERE Word_ID = 2107;
UPDATE Karen_Words SET Pron = 'Ta lu lo' WHERE Word_ID = 2108;
UPDATE Karen_Words SET Pron = 'Ta mu xa' WHERE Word_ID = 2109;
UPDATE Karen_Words SET Pron = 'Ta wi ta kə la' WHERE Word_ID = 2110;
UPDATE Karen_Words SET Pron = 'Ta ʔo Po θə ra' WHERE Word_ID = 2111;
UPDATE Karen_Words SET Pron = 'Ta θa ɣe' WHERE Word_ID = 2112;
UPDATE Karen_Words SET Pron = 'Ta θa su' WHERE Word_ID = 2113;
UPDATE Karen_Words SET Pron = 'To ma ɓu' WHERE Word_ID = 2116;
UPDATE Karen_Words SET Pron = 'Tu lə' WHERE Word_ID = 2118;
UPDATE Karen_Words SET Pron = 'ti ɣu ko θe' WHERE Word_ID = 2122;
UPDATE Karen_Words SET Pron = 'ti ko tə pe' WHERE Word_ID = 2124;
UPDATE Karen_Words SET Pron = 'ʧi no' WHERE Word_ID = 2125;
UPDATE Karen_Words SET Pron = 'to Pu we' WHERE Word_ID = 2132;
UPDATE Karen_Words SET Pron = 'we Ko' WHERE Word_ID = 2136;
UPDATE Karen_Words SET Pron = 'wi tə ma' WHERE Word_ID = 2137;
UPDATE Karen_Words SET Pron = 'xo pu' WHERE Word_ID = 2140;
UPDATE Karen_Words SET Pron = 'xu si' WHERE Word_ID = 2142;
UPDATE Karen_Words SET Pron = 'xu si' WHERE Word_ID = 2142;
UPDATE Karen_Words SET Pron = 'xwe to' WHERE Word_ID = 2143;
UPDATE Karen_Words SET Pron = 'ʔo lə lo θa' WHERE Word_ID = 2150;
UPDATE Karen_Words SET Pron = 'ʔo lə lo θa' WHERE Word_ID = 2150;
UPDATE Karen_Words SET Pron = 'ʔo mu' WHERE Word_ID = 2151;
UPDATE Karen_Words SET Pron = 'ʔo mu' WHERE Word_ID = 2151;
UPDATE Karen_Words SET Pron = 'θa ɣi' WHERE Word_ID = 2154;
UPDATE Karen_Words SET Pron = 'θa he' WHERE Word_ID = 2155;
UPDATE Karen_Words SET Pron = 'θa Ku' WHERE Word_ID = 2156;
UPDATE Karen_Words SET Pron = 'θa Sa ne te' WHERE Word_ID = 2159;
UPDATE Karen_Words SET Pron = 'θa to tʌ' WHERE Word_ID = 2161;
UPDATE Karen_Words SET Pron = 'θa θe ju' WHERE Word_ID = 2162;
UPDATE Karen_Words SET Pron = 'θe la' WHERE Word_ID = 2165;
UPDATE Karen_Words SET Pron = 'θə ne' WHERE Word_ID = 2166;
UPDATE Karen_Words SET Pron = 'θe Pa ɲo' WHERE Word_ID = 2167;
UPDATE Karen_Words SET Pron = 'θə Pə' WHERE Word_ID = 2168;
UPDATE Karen_Words SET Pron = 'θə ro' WHERE Word_ID = 2170;
UPDATE Karen_Words SET Pron = 'θe So' WHERE Word_ID = 2171;
UPDATE Karen_Words SET Pron = 'θe te' WHERE Word_ID = 2172;
UPDATE Karen_Words SET Pron = 'θə to' WHERE Word_ID = 2173;
UPDATE Karen_Words SET Pron = 'θo Ka' WHERE Word_ID = 2175;
UPDATE Karen_Words SET Pron = 'θo Ka Po' WHERE Word_ID = 2176;
UPDATE Karen_Words SET Pron = 'θu Ko pa to' WHERE Word_ID = 2179;
UPDATE Karen_Words SET Pron = 'θu Ku θa ɣo' WHERE Word_ID = 2180;
UPDATE Karen_Words SET Pron = 'θu Ku θa Ku' WHERE Word_ID = 2181;
UPDATE Karen_Words SET Pron = 'θu mu to' WHERE Word_ID = 2182;
UPDATE Karen_Words SET Pron = 'də gə gwe' WHERE Word_ID = 2193;
UPDATE Karen_Words SET Pron = 'də gə gwe jɛ' WHERE Word_ID = 2194;
UPDATE Karen_Words SET Pron = 'də gə ja' WHERE Word_ID = 2195;
UPDATE Karen_Words SET Pron = 'də gə la' WHERE Word_ID = 2196;
UPDATE Karen_Words SET Pron = 'də gə Tɔ' WHERE Word_ID = 2197;
UPDATE Karen_Words SET Pron = 'də gə Tɔ jɛ si' WHERE Word_ID = 2198;
UPDATE Karen_Words SET Pron = 'ə Kɔ Ti' WHERE Word_ID = 2219;
UPDATE Karen_Words SET Pron = 'gə pɔ tə gə ja' WHERE Word_ID = 2243;
UPDATE Karen_Words SET Pron = 'gə pɔ tə si' WHERE Word_ID = 2244;
UPDATE Karen_Words SET Pron = 'kə li so' WHERE Word_ID = 2257;
UPDATE Karen_Words SET Pron = 'kə li Te' WHERE Word_ID = 2258;
UPDATE Karen_Words SET Pron = 'kə tə' WHERE Word_ID = 2259;
UPDATE Karen_Words SET Pron = 'Kɔ mu' WHERE Word_ID = 2263;
UPDATE Karen_Words SET Pron = 'ni ti' WHERE Word_ID = 2292;
UPDATE Karen_Words SET Pron = 'Pɔ jɛ' WHERE Word_ID = 2297;
UPDATE Karen_Words SET Pron = 'Pe ʔi' WHERE Word_ID = 2299;
UPDATE Karen_Words SET Pron = 'tə Pɔ jɛ' WHERE Word_ID = 2328;
UPDATE Karen_Words SET Pron = 'tə si' WHERE Word_ID = 2329;
UPDATE Karen_Words SET Pron = 'tə si Ki' WHERE Word_ID = 2330;
UPDATE Karen_Words SET Pron = 'tə si tə' WHERE Word_ID = 2331;
UPDATE Karen_Words SET Pron = 'θi hu' WHERE Word_ID = 2358;
UPDATE Karen_Words SET Pron = 'θi ɲa' WHERE Word_ID = 2359;
UPDATE Karen_Words SET Pron = 'a lu ʔe' WHERE Word_ID = 2364;
UPDATE Karen_Words SET Pron = 'a ʔi' WHERE Word_ID = 2368;
UPDATE Karen_Words SET Pron = 'a ʔi' WHERE Word_ID = 2369;
UPDATE Karen_Words SET Pron = 'hɨ θa ʔə lu ʔi' WHERE Word_ID = 2390;
UPDATE Karen_Words SET Pron = 'kə ba' WHERE Word_ID = 2409;
UPDATE Karen_Words SET Pron = 'kə ʃɔ' WHERE Word_ID = 2410;
UPDATE Karen_Words SET Pron = 'le mɛ ʔu' WHERE Word_ID = 2435;
UPDATE Karen_Words SET Pron = 'lu ʔi' WHERE Word_ID = 2439;
UPDATE Karen_Words SET Pron = 'me ʔu' WHERE Word_ID = 2446;
UPDATE Karen_Words SET Pron = 'mɛ ʔu pə lu' WHERE Word_ID = 2447;
UPDATE Karen_Words SET Pron = 'no ko' WHERE Word_ID = 2460;
UPDATE Karen_Words SET Pron = 'nu ʔi' WHERE Word_ID = 2461;
UPDATE Karen_Words SET Pron = 'pa ja' WHERE Word_ID = 2465;
UPDATE Karen_Words SET Pron = 'pu we' WHERE Word_ID = 2485;
UPDATE Karen_Words SET Pron = 'ta ta mi mi' WHERE Word_ID = 2505;
UPDATE Karen_Words SET Pron = 'tə ku lə ku i' WHERE Word_ID = 2515;
UPDATE Karen_Words SET Pron = 'u ʔə' WHERE Word_ID = 2536;
UPDATE Karen_Words SET Pron = 'wa wa' WHERE Word_ID = 2540;
UPDATE Karen_Words SET Pron = 'a dɔ gə də' WHERE Word_ID = 2578;
UPDATE Karen_Words SET Pron = 'a hɛ' WHERE Word_ID = 2579;
UPDATE Karen_Words SET Pron = 'a wɛ ne' WHERE Word_ID = 2581;
UPDATE Karen_Words SET Pron = 'a wɛ θi' WHERE Word_ID = 2585;
UPDATE Karen_Words SET Pron = 'bu dɛ ma' WHERE Word_ID = 2589;
UPDATE Karen_Words SET Pron = 'bwa ma ta Pɔ ʔa mu ni' WHERE Word_ID = 2596;
UPDATE Karen_Words SET Pron = 'bwa θa wi ta Po' WHERE Word_ID = 2598;
UPDATE Karen_Words SET Pron = 'bwa θo Po' WHERE Word_ID = 2599;
UPDATE Karen_Words SET Pron = 'dɔ du' WHERE Word_ID = 2602;
UPDATE Karen_Words SET Pron = 'dɔ ma' WHERE Word_ID = 2603;
UPDATE Karen_Words SET Pron = 'də ɣi nɔ də sɛ pa' WHERE Word_ID = 2605;
UPDATE Karen_Words SET Pron = 'də ɣi pa' WHERE Word_ID = 2606;
UPDATE Karen_Words SET Pron = 'de ɲa' WHERE Word_ID = 2607;
UPDATE Karen_Words SET Pron = 'gɔ Ku ʔa mu ni' WHERE Word_ID = 2611;
UPDATE Karen_Words SET Pron = 'gə ði də ɽa mu' WHERE Word_ID = 2612;
UPDATE Karen_Words SET Pron = 'gə jɔ' WHERE Word_ID = 2613;
UPDATE Karen_Words SET Pron = 'ge jɔ gə də' WHERE Word_ID = 2614;
UPDATE Karen_Words SET Pron = 'gə jɔ nɨ dɨ' WHERE Word_ID = 2615;
UPDATE Karen_Words SET Pron = 'gwɛ hu Pə la' WHERE Word_ID = 2619;
UPDATE Karen_Words SET Pron = 'Kɔ Pə' WHERE Word_ID = 2627;
UPDATE Karen_Words SET Pron = 'Kli ʔɔ Pə lɛ' WHERE Word_ID = 2630;
UPDATE Karen_Words SET Pron = 'Ko θə Kə' WHERE Word_ID = 2631;
UPDATE Karen_Words SET Pron = 'la hɔ' WHERE Word_ID = 2633;
UPDATE Karen_Words SET Pron = 'lɔ dɛ' WHERE Word_ID = 2636;
UPDATE Karen_Words SET Pron = 'lɔ dɛ' WHERE Word_ID = 2637;
UPDATE Karen_Words SET Pron = 'lɔ hi' WHERE Word_ID = 2638;
UPDATE Karen_Words SET Pron = 'lɔ Kɔ θə lo' WHERE Word_ID = 2640;
UPDATE Karen_Words SET Pron = 'lə ne də Pa ne' WHERE Word_ID = 2642;
UPDATE Karen_Words SET Pron = 'ma Tɔ ɾa ʔa mu ni' WHERE Word_ID = 2644;
UPDATE Karen_Words SET Pron = 'mə ta lɛ' WHERE Word_ID = 2645;
UPDATE Karen_Words SET Pron = 'me Ti' WHERE Word_ID = 2646;
UPDATE Karen_Words SET Pron = 'mo ʔa mu ni' WHERE Word_ID = 2648;
UPDATE Karen_Words SET Pron = 'mu nak' WHERE Word_ID = 2649;
UPDATE Karen_Words SET Pron = 'nɔ də' WHERE Word_ID = 2650;
UPDATE Karen_Words SET Pron = 'nə θu' WHERE Word_ID = 2653;
UPDATE Karen_Words SET Pron = 'ni Tɔ ʔa mu ni' WHERE Word_ID = 2655;
UPDATE Karen_Words SET Pron = 'no ge de ɔ da' WHERE Word_ID = 2656;
UPDATE Karen_Words SET Pron = 'pa ʔa mu ni' WHERE Word_ID = 2658;
UPDATE Karen_Words SET Pron = 'Pa Tɔ' WHERE Word_ID = 2659;
UPDATE Karen_Words SET Pron = 'Pa θa' WHERE Word_ID = 2660;
UPDATE Karen_Words SET Pron = 'Plɔ Ki' WHERE Word_ID = 2662;
UPDATE Karen_Words SET Pron = 'Plo Ki Pu Kɔ' WHERE Word_ID = 2664;
UPDATE Karen_Words SET Pron = 'pwa Pa nə ta pɔ ta li ʔa ɔ' WHERE Word_ID = 2668;
UPDATE Karen_Words SET Pron = 'sɛ ma ɣi da' WHERE Word_ID = 2669;
UPDATE Karen_Words SET Pron = 'sɛ ʃu da' WHERE Word_ID = 2670;
UPDATE Karen_Words SET Pron = 'Sɔ nɔ Ko ʔɔ mi' WHERE Word_ID = 2671;
UPDATE Karen_Words SET Pron = 'ta gɔ Ka' WHERE Word_ID = 2674;
UPDATE Karen_Words SET Pron = 'ta ge ɲa To ta' WHERE Word_ID = 2675;
UPDATE Karen_Words SET Pron = 'ta ma gu ɾɔ da ʔɔ' WHERE Word_ID = 2677;
UPDATE Karen_Words SET Pron = 'ta pa Tɔ li ʔa lɔ' WHERE Word_ID = 2678;
UPDATE Karen_Words SET Pron = 'ta ʔɛ ʔa mu ni' WHERE Word_ID = 2681;
UPDATE Karen_Words SET Pron = 'ta θa wi' WHERE Word_ID = 2682;
UPDATE Karen_Words SET Pron = 'Tɔ gə də' WHERE Word_ID = 2685;
UPDATE Karen_Words SET Pron = 'Tɛ gu' WHERE Word_ID = 2687;
UPDATE Karen_Words SET Pron = 'wi θa Su' WHERE Word_ID = 2702;
UPDATE Karen_Words SET Pron = 'ʔa bɔ nɨ dɨ' WHERE Word_ID = 2703;
UPDATE Karen_Words SET Pron = 'ʔa bə ʔa mu ni' WHERE Word_ID = 2704;
UPDATE Karen_Words SET Pron = 'ʔa ɕa nɨ dɨ' WHERE Word_ID = 2705;
UPDATE Karen_Words SET Pron = 'ʔa hɛ gə də' WHERE Word_ID = 2707;
UPDATE Karen_Words SET Pron = 'ʔa Pu gə də' WHERE Word_ID = 2709;
UPDATE Karen_Words SET Pron = 'ʔa ʔa' WHERE Word_ID = 2711;
UPDATE Karen_Words SET Pron = 'ʔa ʔi' WHERE Word_ID = 2712;
UPDATE Karen_Words SET Pron = 'ʔa ʔi də Pa ʔi' WHERE Word_ID = 2713;
UPDATE Karen_Words SET Pron = 'ʔə ʁi' WHERE Word_ID = 2714;
UPDATE Karen_Words SET Pron = 'θa Sa' WHERE Word_ID = 2719;
UPDATE Karen_Words SET Pron = 'θa Sa gə də' WHERE Word_ID = 2720;
UPDATE Karen_Words SET Pron = 'θa Sa nɨ dɨ' WHERE Word_ID = 2721;
UPDATE Karen_Words SET Pron = 'θə li' WHERE Word_ID = 2722;
UPDATE Karen_Words SET Pron = 'θi mu' WHERE Word_ID = 2724;
UPDATE Karen_Words SET Pron = 'θi sa' WHERE Word_ID = 2725;
UPDATE Karen_Words SET Pron = 'jɛ gə də' WHERE Word_ID = 2733;
UPDATE Karen_Words SET Pron = 'kɛ ʔi baʔ' WHERE Word_ID = 2734;
UPDATE Karen_Words SET Pron = 'lɔ ʁə' WHERE Word_ID = 2736;
UPDATE Karen_Words SET Pron = 'o we θi' WHERE Word_ID = 2740;
UPDATE Karen_Words SET Pron = 'Pa jɛ' WHERE Word_ID = 2741;
